"""Generate docs/stats_reference.md from the statistic registry.

    python behav_utils/docs/gen_stats_reference.py        # rewrites the file next to this script

The document is the registry's own view of itself — producer, outputs, exchangeability and the
producer's docstring — so it cannot drift from the code. Edit the prose header here; edit a stat's
description in its docstring.
"""

from __future__ import annotations

import inspect
from pathlib import Path

HEADER = '''# Summary statistics reference

Generated by `docs/gen_stats_reference.py` from `behav_utils.stats` — do not edit the tables by hand.

## The contract

A **statistic** is a float computed from a `TrialArrays`. Every producer has the signature
`f(arrays, *, rng) -> float` (or a tuple of floats for a fitter). Two decorators register them:

```python
from behav_utils.stats import stat, fit

@stat('my_rate')                                  # one scalar
def my_rate(arrays, *, rng):
    return float(arrays.choice.mean())

@fit('my_fit', outputs=('a', 'b'), exchangeable=False)   # one fitter, several named outputs
def my_fit(arrays, *, rng):
    ...
    return a, b
```

`compute_stats(arrays, names)` returns a float `pd.Series` indexed by the requested names, in request
order; a fitter runs once however many of its outputs are requested. `PSYCHOMETRIC` expands to
`('mu', 'sigma', 'lapse_low', 'lapse_high')` and `PSE_DYNAMICS` to the `pse_*` outputs.

```python
from behav_utils import pool_arrays, compute_stats, list_stats, PSYCHOMETRIC
arrays = pool_arrays(clean)                       # clean = filter_trials(select_sessions(...))
s = compute_stats(arrays, ['accuracy', 'recency', *PSYCHOMETRIC])
s['mu'], s['accuracy']
list_stats()                                      # every scalar name
```

**Exchangeable** means trial-level resampling (bootstrap, matched-n draws) is valid for the producer:
memoryless and lag-1 statistics use the frozen `prev_*` view and are safe; anything that depends on
trial order beyond lag 1 is not, and the resamplers refuse it (`is_exchangeable(name)`). Session-level
resampling (`unit='sessions'`) is valid for every stat.

Array-valued readouts — the psychometric curve, update matrix, conditional psychometric, binned
curve, serial-dependence profile — are not statistics; they live in `behav_utils.readouts` as
dataclasses with one draw-only plotter each.

Stimulus is on the normalised axis with the boundary at 0; category B is the positive side; `choice`
is 1 for B. "Hard" trials are `|stimulus| < HARD_THRESHOLD` (0.3 by default).

'''


def _doc(func) -> str:
    d = inspect.getdoc(func) or ''
    return d.strip()


def build() -> str:
    from behav_utils.stats.registry import _PRODUCERS

    groups: dict[str, list] = {}
    for entry in _PRODUCERS.values():
        module = entry.func.__module__.split('.')[-1]
        groups.setdefault(module, []).append(entry)

    titles = {'basic': 'Performance and bias', 'psychometric': 'Psychometric fit',
              'history': 'Trial history and serial dependence', 'dynamics': 'Within-block PSE dynamics',
              'rt': 'Reaction time'}
    out = [HEADER, '## Index\n\n| scalar | producer | module | exchangeable |\n|---|---|---|---|\n']
    for module, entries in groups.items():
        for e in entries:
            for o in e.outputs:
                out.append(f'| `{o}` | `{e.name}` | {module} | {"yes" if e.exchangeable else "no"} |\n')
    out.append('\n')
    for module, entries in groups.items():
        out.append(f'## {titles.get(module, module)} (`stats/{module}.py`)\n\n')
        for e in entries:
            kind = 'fitter' if len(e.outputs) > 1 or e.outputs[0] != e.name else 'stat'
            out.append(f'### `{e.name}` ({kind}; exchangeable: {"yes" if e.exchangeable else "no"})\n\n')
            if kind == 'fitter':
                out.append('Outputs: ' + ', '.join(f'`{o}`' for o in e.outputs) + '\n\n')
            out.append(_doc(e.func) + '\n\n')
    return ''.join(out)


def main():
    target = Path(__file__).with_name('stats_reference.md')
    target.write_text(build())
    print(f'wrote {target}')


if __name__ == '__main__':
    main()
